#!/usr/bin/env bash
# Runs ON THE VM (as root) during every deploy: builds /opt/plc-dashboard/.env from
#   deploy/gcp-settings.env      non-secret settings (host names, ports, ...)
#   Secret Manager       secrets listed in deploy/secrets.list, read with the VM's own
#                        service account (it may read only plc-* secrets)
# The resulting file is root-only (600); Docker Compose needs it to start the containers.
set -euo pipefail
cd "$(dirname "$0")/.."

tmp="$(mktemp .env.XXXXXX)"
trap 'rm -f "$tmp"' EXIT
chmod 600 "$tmp"
{
  echo "# Generated by deploy/fetch-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) from gcp-settings.env + Secret Manager."
  echo "# Do not edit: change deploy/gcp-settings.env or the secret, then redeploy."
  cat deploy/gcp-settings.env
  echo
} > "$tmp"

while read -r var name flags; do
  [ -z "${var:-}" ] && continue
  case "$var" in \#*) continue ;; esac
  if ! value="$(gcloud secrets versions access latest --secret="$name" 2>/dev/null </dev/null)"; then
    if [ "${flags:-}" = "optional" ]; then continue; fi
    echo "ERROR: cannot read secret '$name' from Secret Manager" >&2
    exit 1
  fi
  case "$value" in
    *"'"* | *$'\n'*) echo "ERROR: secret '$name' must not contain quotes or newlines" >&2; exit 1 ;;
  esac
  printf "%s='%s'\n" "$var" "$value" >> "$tmp"
done < deploy/secrets.list

mv "$tmp" .env
trap - EXIT
echo "    .env built from gcp-settings.env + $(grep -cE "^[A-Z_]+='" .env) secrets"
